[package]
name = "backend-rust-lib"
version = "0.1.0"
description = "Library for RealWorld"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
